export const images = {
  favicon: '/favicon.ico',
  logo: '/logo_tc_store.png',
  icons: {
    avatarDefault: '/assets/images/Icons/avatarDefault.png',
    iconZalo: '/assets/images/Icons/iconZalo.png',
    iconHome: '/assets/images/Icons/iconHome.png',
    iconMyUser: '/assets/images/Icons/iconMyUser.png',
    iconLoadingModal: '/assets/images/Icons/iconLoadingModal.png',
    iconCheckBoxSelected: '/assets/images/Icons/iconCheckBoxSelected.svg',
    iconCheckBox: '/assets/images/Icons/iconCheckBox.svg',
    iconOptionPayment: '/assets/images/Icons/iconOptionPayment.png',
    iconMomo: '/assets/images/Icons/iconMomo.png',
    iconWarning: '/assets/images/Icons/iconWarning.png',
    iconDiscount: '/assets/images/Icons/iconDiscount.png',
    iconBill: '/assets/images/Icons/iconBill.webp',
    iconHistory: '/assets/images/Icons/iconHistory.png',
    iconOrder: '/assets/images/Icons/iconOrder.png',
    iconBack: '/assets/images/Icons/iconBack.png',
    iconCart: '/assets/images/Icons/iconCart.png',
    iconShield: '/assets/images/Icons/iconShield.png',
    iconSupport: '/assets/images/Icons/iconSupport.webp',
    iconResponsibility: '/assets/images/Icons/iconResponsibility.webp',
    iconHeart: '/assets/images/Icons/iconHeart.png',
    iconHeart1: '/assets/images/Icons/iconHeart1.png',
    iconUpdating: '/assets/images/Icons/iconUpdating.webp',
    iconSuccess: '/assets/images/Icons/iconSuccess.png',
    iconShoppe: '/assets/images/Icons/iconShoppe.png',
    messenger: '/assets/images/Icons/iconMessager.png',
    iconDelete: '/assets/images/Icons/iconDelete.png',
    iconFacebook: '/assets/images/Icons/iconFaboook.png',
    iconChecked: '/assets/images/Icons/iconChecked.png',
    iconSuccessGif: '/assets/images/Icons/iconSuccess.gif',
    unknowTokenIcon: '/assets/images/Icons/unknowTokenIcon.png',
    iconMessageChat: '/assets/images/Icons/iconMessageChat.png',
  },
  home: {
    banner: '/assets/images/Home/banner.webp',
  },
}
